### ISSUE TITLE
Minor data reading error/glitch in the totalCost field

### ISSUE THREAD

**Issue by mohabazzi** [KTH-Library/cordis#5]
Noterade att totalCost fältet som finns i 'he_project' har lästs in utan decimaler vilket gör vissa anslag väldigt stora. En work around i R är att behandla de sista två sifforna som tiondelar? för alla värden >7.

**Comment by mskyttner** [comment]
Use locale setting for read_delim:

```
locale = readr::locale(decimal_mark = ","))
```

some are off with a factor of 10 (700+) some with a factor of 100 (1300+) and some are correct.
